version: '3.0'
services:
  dev.back.crm.local:
    image: 'vllanten/php731_composer:2'
    volumes:
      - './[PATH-TO-SUITECRM]:/var/www/html'
      # - './[PATH-TO-ZF3-GENERATOR]:/var/www/zf3-code-generator-suite-crm'
    ports:
      - '81:80'
  api.crm.local:
    image: 'node:8'
    working_dir: '/var/www/html'
    volumes:
      - './[PATH-TO-BACK-NODE]:/var/www/html'
    ports:
      - '3000:3000'
    command: 'npm run dev'
  proxy:
    image: 'nginx:1.13'
    volumes: 
      - './localProxy/crm.conf:/etc/nginx/conf.d/crm.conf'
      - './localProxy/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
